### ISSUE TITLE
Помощь Требуемое

### ISSUE THREAD

**Issue by nomiyousafzai** [forth32/balong-usbdload#1]
Здравствуй,
мне нужно USB-5330bs.bin безопасный
i need safe usb loader for Huawei E5330bs

**Comment by forth32** [comment]
И где я его тебе возьму?
-- 
Alexander Stepanov

**Comment by nomiyousafzai** [comment]
https://drive.google.com/open?id=0B75K70WRTN28VWhSUkhwUkFfdkU

ссылка для скачивания

**Comment by nomiyousafzai** [comment]
Уважаемый ждет вашего рода ответ ...
