### ISSUE TITLE
e8372h loader problem

### ISSUE THREAD

**Issue by chipoza** [forth32/balong-usbdload#10]
I am not able to lower my e8372h-153. 
operator Zong CMPak Pakistan. 
firmware version 21.318.01.02.306. 
safe and original loader also does not work and gives an error 
link is also attached.
http://4pda.ru/forum/index.php?showtopic=678549&st=1400#entry54916395

**Comment by chipoza** [comment]
in this firmware version 21.318.01.02.306 partition size change from 5.8mb to 5.3 mb.and active kernal when we use these  loader usbloader.bin or usblsalf.bin then kernal restore nv ram.
solution ;>
you patch loader who deactivate firstly kernal and after boot write

**Comment by hassansagar78** [comment]
e8372 21.318.01.02.306 not accept any loader now on this version 
need to find a new loader

**Comment by naeemkkk** [comment]
Same Problem With Me :( My Zong E8372h-153 Not Loading Usblsafe.bin File But How Can I Solve It Please Experts Help Me :(

**Comment by Mohsan123** [comment]
@naeemkkk  use e5573cs-usbloader.bin . this will work.

**Comment by naeemkkk** [comment]
@Mohsan123 bro this file is loaded but firmware is not update any soulation please do you have any firmware working  please suggest me bro.

**Comment by Mohsan123** [comment]
yup! I have working firmware. fw 21.318.01.02.306. problem is nvram clear after updating by this firmware.

**Comment by naeemkkk** [comment]
@Mohsan123  Please can you give me the firmware?

**Comment by Mohsan123** [comment]
yes offcourse.

**Comment by balwinder27** [comment]
Forth32 and Mohson 123 both are greedy persons 
I put comment greedy forth32 locked the thread 
Shame on you both peoples

**Comment by balwinder27** [comment]
Without usbloader forth 32 is zero 
If you are too programmer then make a 1 usbloader 

Just copy loaders from huawei servers then just patch from huawek database 
Then just modify a firmwares 
Forth32  don't think you are no1 because without huawei loader  you are zero

**Comment by wsw243** [comment]
who want zong E5573cs-322 solution contact me on skype WSW243
