### ISSUE TITLE
E3131i-2

### ISSUE THREAD

**Issue by Terminator8** [forth32/balong-usbdload#11]
Hello
Can you find usbloader.bin for this model or perhaps "how to" for retrieval by firmware or modem that works?
Thanks in advance.

**Comment by chipoza** [comment]
i can not find this model usbloader.bin you try all model usblsalf.bin in forth32 project and try with this.maybe any loader work.

**Comment by forth32** [comment]
E3131 is Balong V3 based modem, not Balong v7. I am not sure that this program can download usbloader for V3 chipset. And do not try usbloaders from this repository - these only  for Balong V7.

**Comment by Terminator8** [comment]
Thank you both for the quick response.

**Comment by balwinder27** [comment]
https://drive.google.com/file/d/0B3pEUGa_GFBrS01XLU4zM2I1RHc/view

e8372h-153 zong free solution for everyone

**Comment by balwinder27** [comment]
https://drive.google.com/file/d/0B3pEUGa_GFBrS01XLU4zM2I1RHc/view

e8372h-153 zong free solution for everyone
