### ISSUE TITLE
nvram restore

### ISSUE THREAD

**Issue by abassi94** [forth32/balong-usbdload#14]
hi forth32 
i read your analysis off the fast boot problem you said the nvram is automatically restored 
but i in my b310s 927 it does not 
it stays empty i have lost imei annd serial  number is there any way i can restore it 
thnx

**Comment by The-BigNoob** [comment]
i have found this file 
https://github.com/forth32/balong-usbdload/blob/master/usbloader-b310.bin
with  this firmware ( B310s-927TCPU-V200R001B110D99SP02C00_Firmware_general_05021QJS ) 
the same file 
so this usbloader is patched or not ?? because all nv data  wiped. i backup only (mnvm2:0/nv.bin)
sir forth32 we need help plz

**Comment by chipoza** [comment]
you can fix this manually
for imei repair
at^datalock="12345678"
AT^cimei="15 digit imei"
for seriel no. repair
It is necessary to translate the serial number string into a sequence of codes and written in the NVRAM AT-command.
For example, the serial J5HBYA93C3042173 should be written as follows:
AT ^ DATALOCK = "unlock code"
the AT ^ = NVWR 6,20,4A 35 48 42 59 41 39 33 43 33 30 34 32 31 37 33 FF FF FF FF

**Comment by forth32** [comment]
To enter new serial number, yuo can use command

at^sn=serial

**Comment by chipoza** [comment]
bro can we repair mac adress?

**Comment by The-BigNoob** [comment]
nothing happen it's impossible to repair imei and serial number with AT command

Oem and Nck on my device ALL 000000000

^NVRDEX: 50502,0,128, 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

^NVRDEX: 50503,0,128, 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

sir forth32 if usblsafe repair Oem and Nck please make usblsafe for B310s
or any other method 

thank you

**Comment by abassi94** [comment]
Big noob can you upload the 
Backup

**Comment by abassi94** [comment]
Forth can you complie the patch tool for 
Windows .
I could not run in linux

**Comment by freereial** [comment]
Hello .. how to solve the light power in modem b310-927 What is the update user programs .... Please help me

**Comment by chipoza** [comment]
contact to me i will solve all user problem.only b310-927 //// icq uin 704208779

**Comment by hassansagar78** [comment]
if we repair manualy imei and serial number it works fine but the problem is device didnt reset anymore...
how to fix reset issue manualy except restore nv?

**Comment by brightosky27** [comment]
b315 safe loader works for b310 as well

**Comment by brightosky27** [comment]
i dont get explain again

**Comment by forth32** [comment]
Firmware from balwinder27 requires mkey dongle (it is in mkey .cbin format), therefore, this is mkey marketing. In this reason, i will block all balwinder27 messages in future.

Don not convert this issue threads to market trash. Use mkey forums fo it.
