### ISSUE TITLE
E5770 boot pin

### ISSUE THREAD

**Issue by For34** [forth32/balong-usbdload#18]
anyone knows how to unlock E5770 huawei ?

and boot pin image ?

please share

**Comment by Zaraky2008** [comment]
check this link

https://routerunlock.com/boot-pin-of-different-huawei-hi-silicon-modem-and-router/

**Comment by balwinder27** [comment]
Forth32 if you have sense to listen truth then face it 
You delete our comment and prove here you are lier just steal huawek database and make fool to peoples 

You have original huawei source patch a loader and modify a firmware
