### ISSUE TITLE
balong-usbdload CMD command 

### ISSUE THREAD

**Issue by hermann-franck** [forth32/balong-usbdload#19]
Hi, 
what is the CMD command for this tool to load an .bin file please.
Thanks

**Comment by chipoza** [comment]
for example your com port is com1 .command is below.
balong_usbdload -p1 usbloader.bin and after this command hit enter
for fastboot mode
balong_usbdload -p1 -f usbloader.bin

**Comment by naeemkkk** [comment]
@chipoza dear do you have any method for E8372h-153 in latest firmware?

**Comment by balwinder27** [comment]
https://drive.google.com/file/d/0B3pEUGa_GFBrS01XLU4zM2I1RHc/view

e8372h-153 zong free solution for everyone
