### ISSUE TITLE
Zong CmPak E5573Cs-322 .

### ISSUE THREAD

**Issue by BKHNS** [forth32/balong-usbdload#20]
@forth32 @rust3028 
Your assistance is required with regard to **E5573Cs-322** having a **signed** firmware version **21.318.03.01.306**. 
The loader helped in erasing NV contents and then the device downgraded successfully to 
21.318.99.03.00, i was also able to restore the NV contents later but after upgrading to 21.318.03.00.00, the device remains in dead mode. 
Please help me out if you find it appropriate, thankyou.

**Comment by wasifmobileshop** [comment]
hi
E5573Cs-322 unlock don 2g signal not 3g and 4g signal ok pless sir solve my problem E5573cs_UPDATE_21.318.09.00.00 thinks

**Comment by wsw243** [comment]
@BKHNS 
contact with me on skype WSW243

**Comment by forth32** [comment]
Please do not convert this issues to commercial forum!!!

**Comment by chipoza** [comment]
dear @wasifmobileshop @BKHNS forth32 is working on e5573cs-322 .it will gave solution to people as soon as possible.and thanks  again forth32 for e8372h unlock.

**Comment by BKHNS** [comment]
Thank you @chipoza for the reply.

**Comment by chipoza** [comment]
according to forth32 some pakistani people gave e8372 solution to mkey admin . mkey add this fw in our support area .due to this fort32 is not reply pakistani people.but that is not true .india guy blwinder27 leack this fw.

**Comment by Mohsan123** [comment]
according to e8372h solution by hassansagar and blwinder27, all nvram data will be wiped. so it is not safe solution as compare to forth32 provided solutions.

**Comment by Mohsan123** [comment]
according to e8372h solution by hassansagar and blwinder27, all nvram data will be wiped and this is also not free. so it is not safe solution as compare to @forth32 provided solutions that's free of cost.

**Comment by shah-95** [comment]
@chipoza what was the solution for e8372h-153 unlock ??

**Comment by chipoza** [comment]
we have safe solution but this solution is not shareable due to market reason . solution created by my teacher forth32  .(world first time)

**Comment by shah-95** [comment]
if it is free then why not share it bro , i am not any seller or repairer , i want only to make my own device working , if you cannot share the solution , then you and others that charge hefty amount are the same , sorry to say bro this is not the good way of life

**Comment by chipoza** [comment]
the owner of this solution is forth32 . i can not leak without fort32 permission . forth32 will release final version for e8327 .in this time have some bugs mac address etc. if you want own device in working you just 
boot pin and load usbload.bin and simply run e5573cs-322 orignal fw. after update your device will be in working condition .

**Comment by shah-95** [comment]
ok dear , no problem , i already know this , just wanted a patched firmware for working with other networks bro , i believe in this that if you get helped for free , help others for free , if you ever could give me patched fw it would be much kind of you , regards.

**Comment by chipoza** [comment]
This is helping project (no paid like mkey). forth32 will release e5573cs-322 solution but wait some time because have some bugs.i know some people created solution but this solution is not full also have some bugs . 2g not work , no stability , reset button issue , etc.

**Comment by shah-95** [comment]
@chipoza yes u are absolutely correct , i am having the same issues bro , i want your help bro , can you contact me at ali_hassan_shah19@yahoo.com , thank you very much

**Comment by renoos** [comment]
hi to all .. i am here new . and first i want to thank you sir forth32 for making free solution .

**Comment by shah-95** [comment]
can this FREE solution not be shared ??? why we had to pay heavily to some who get this solution for free ???

**Comment by chipoza** [comment]
This is only a helping section . We not demand pay .

**Comment by Mohsan123** [comment]
We are waiting solution for e8372h-153, e8372h-608 & e5577cs having latest firmware,
We hope Great Sir Forth32 will provide as soon as possible.
someone who have this solution is not complete solution.

**Comment by chipoza** [comment]
We can not leak solution due to mkey marketing .it has some -ve rezult .if we leack openly then operater will update software and other due to market reason we can not show this method openly . If you want to unlock this device need to learn more and judge the security  and more .otherwise we can no performer any action without forte32 permission .if you have any question contect with me alivekhanpk@gmail.com

**Comment by BKHNS** [comment]
@forth32 , KIndly grant that (PERMISSION) that everybody on every form keeps talking about. 
If possible kindly contact me at: burhankhans@outlook.com. 
**I don't need your solution for any profit motive, the only reason is to restore my device into working condition.** 
Pls respond if appropriate.

**Comment by hassansagar78** [comment]
@mohsan123 bro stop blaming me..if you have any personal issue than email me hassansagar78 @gmail.com and for your kind information I hv both safe solutions zong 5573cs-322 and zong 8372h-153

**Comment by chipoza** [comment]
@mohsin Please dont use immortel language otherwise you Will we banned. As
à rezult forte32 can not help to pakistani Person .please do not use bad
language request to all .

**Comment by tanveerahmad6506** [comment]
zong green logo unlocking 1000% ok...
skype id: tanveer6506@hotmail.com
