### ISSUE TITLE
Lost MAC ADDRESS 

### ISSUE THREAD

**Issue by tipaksikil** [forth32/balong-usbdload#22]
Sir, on B310 I lost wLAN and LAN MAC address. How to write new MAC address?

**Comment by chipoza** [comment]
why you want to write mac address?this is not important .only repair imei, seriel, etc

**Comment by tipaksikil** [comment]
I have trouble, about ARP table when connecting mikrotik.

**Comment by ValdikSS** [comment]
You can change MAC address with AT^PHYNUM AT command.

**Comment by chipoza** [comment]
if mac adress is 74:A5:28:FE:3A:96
then at command (at^74:A5:28:FE:3A:96)?

**Comment by ValdikSS** [comment]
```
AT^PHYNUM?
                        
^PHYNUM:IMEI,354282071762468
^PHYNUM:MAC,9CB2B2DCA764
^PHYNUM:MACWLAN,9CB2B2DCA765,0,3
^PHYNUM:SVN,00
```

```
AT^PHYNUM=MAC,74A528FE3A96
```
