### ISSUE TITLE
lost imei and serial of e8231s-1

### ISSUE THREAD

**Issue by Mohsan123** [forth32/balong-usbdload#25]
i lost imei and serial number after flashing my device with no patched usbloader.bin
how to restore it?
AT^cimei="15 digit imei"

above command return error +CME ERROR: 1

**Comment by chipoza** [comment]
1>at^cardlock="xxxxxxxx"
x is unlock coad
>at^ciemi"15 digit imei"

**Comment by Mohsan123** [comment]
Thanks So Much @chipoza .
now it accept imei but there is no sim signals found. now what to do?

**Comment by chipoza** [comment]
find any unlock device and connect with pc as debug mode .open efs tool and backup NV_DATA(must know ip-ranges ) and restore in this device.

**Comment by Mohsan123** [comment]
@chipoza  dear, where from I get efs tool for backup nv_data?
