### ISSUE TITLE
zong e5573cs-322 not reset please help forth32 sir

### ISSUE THREAD

**Issue by anix22** [forth32/balong-usbdload#28]
sir i have zong e5573cs-322

after unlock reset button not work

please help me great forth32 sir

**Comment by chipoza** [comment]
forth32 not want to show this reset button fixsation solution due to mkey marketing .do not ask next time in this type of question if you want to really fix this you learn more and more ..

**Comment by anix22** [comment]
I AM NOT A PROGRAMER THEN HOW YOU SAY LEARN MORE AND MORE

**Comment by saqi755** [comment]
Respectable sir i try to unlock E8231s-2 after using original usbloader i succeeded in unlocking but now my device cant show signal of any network no signals issue how can i repair it please someone help me

**Comment by ronix889** [comment]
repair imei then check

**Comment by saqi755** [comment]
Can any expert  guide me to make a backup of huawei E8231s wingles nv data and restore procedure ? Waiting for a good response from some good people.

**Comment by Mohsan123** [comment]
@saqi755  you have to contact nearest Huawei repair center. I have also done this kind of job and lost NV-data unfortunately. After this I contact to my nearest Huawei center for repairing my device.

**Comment by saqi755** [comment]
Huawei Center replied in negative

**Comment by Mohsan123** [comment]
contact with Huawei on web chat. they will guide best repairing center.

**Comment by mohish1** [comment]
https://drive.google.com/file/d/0B7JLyYkSo1rFdmthWmtmMWY1RDg/view?usp=sharing

telenor latest e8372h-608 21.316.01.04.274+reset solution thans to my frend ibrahim who share me reset solution
