### ISSUE TITLE
Huawei E8231 

### ISSUE THREAD

**Issue by hassansagar78** [forth32/balong-usbdload#3]
Sir
sub: Huawei E8231s-1 usblsafe required.
the given loader delete all nvram data & device doesn't carry signals on any firmware.
kindly make usblsafe for given loader. 

https://drive.google.com/open?id=0B2d5risc67IVTnlESWRwOGJVTE0

A Huge Thanks

**Comment by alirazam** [comment]
janu patched the loader

**Comment by hassansagar78** [comment]
kindly add the safe loader for 8231 in your project...new balong_usbdload latest build not apply patch on the fly for this device

**Comment by praveen02008** [comment]
My Huawei's E8231s-1 not able to flsh please add the safe loader
