### ISSUE TITLE
 balongnvtool.exe how to use

### ISSUE THREAD

**Issue by anix22** [forth32/balong-usbdload#30]

**Comment by renoos** [comment]
@anix22 
sir i have huawei e5330bs-2 want to unlock . i done boot shot then i run usbdload with cmd command 
![e5330](https://cloud.githubusercontent.com/assets/27152777/25627642/b3e679fc-2f7c-11e7-996d-5d6e4e25f990.jpg)

**Comment by ronix889** [comment]
anyone help how to use balong nv tool.exe

**Comment by chipoza** [comment]
if pc ui interface is com1
balong_usbdload -p1 usblsalf-5330.bin

**Comment by renoos** [comment]
@chipoza  after boot shot pin . i have com 12  i try this command balong_usbdload -p12 usblsalf-5330.bin but is not working then i try this command balong_usbdload -c usblsalf-5330.bin i got this error as i was attach the picx . please help me now what i do ?

**Comment by ronix889** [comment]
no one have knowledge how to backup nv.imh nv.default nv.dload
strange thing

**Comment by ronix889** [comment]
dear renoos bro here no one help to our  normal users seems

**Comment by ronix889** [comment]
here only help people which are spechial peoples 

we normal users no one reply no one help
