### ISSUE TITLE
e5776 usbloader 

### ISSUE THREAD

**Issue by kurdpasha** [forth32/balong-usbdload#35]
pleas can u creat e5776 usbloader

**Comment by chipoza** [comment]
find usboader.bin in eassyfirmware.com or dlgsm.com or asanfile.com.

**Comment by aalirazamanzoor** [comment]
telenor e8372h21.316.01.04.274  solution+reset
https://drive.google.com/file/d/0Bx5FFDeIQ2szX2RQTG9qNTdSRHc/view?usp=sharing
