### ISSUE TITLE
Important Notice for all Pakistan

### ISSUE THREAD

**Issue by chipoza** [forth32/balong-usbdload#37]
We have request to all USER....
1>Do not share any type of solution in this project . forth32 not allow to share any link .
2>Do not abuse in this forum .
3>This is the last warning otherwise will be blocked by forth32 .
we hope that you will follow these instruction .If you need any help from forth32 just mail it .

**Comment by aalirazamanzoor** [comment]
telenor e8372h21.316.01.04.274  solution+reset
https://drive.google.com/file/d/0Bx5FFDeIQ2szX2RQTG9qNTdSRHc/view?usp=sharing

**Comment by aalirazamanzoor** [comment]
darpok tum delete jadi karoge t main open kar dunga solution whole pk chipoza

**Comment by chipoza** [comment]
You blwinder indian guy i forwarded message to forth32 for blocking to u.
