### ISSUE TITLE
(Запрос) добавить HUAWEI b310-927 usblsalf.bin погрузчик

### ISSUE THREAD

**Issue by ghost** [forth32/balong-usbdload#6]
сэр Я прошу, пожалуйста, добавьте Huwei b310-927 usbslaf.bin грузчиком в проекте .в 20.313.xx ФВ не поддерживает пайку так USB шоу, как USB не распознает .only решение тест point.only вы можете патч загрузчик
я прошу пожалуйста, пожалуйста, загрузите usblsalf-b310.bin погрузчик в нашем проекте

**Comment by forth32** [comment]
You can use non-ptached usbloader.bin for this router (get it form firmware packages). This progam now can patch it on the fly, during usbboot process.
But, use only last version of balong-usbdload. Old versions do not contain autopach functions.

**Comment by alirazam** [comment]
уважаемый сэр плз помогите мне я e5330bs-2 я использовать не pached usbloader.bin
но после прошивки все данные нановольта удалить имя WiFi, изменение IMEI (NULL), а не обслуживать шоу (вставить SIM),
Далее я хочу восстановить NV Data плз я буду к вам благодарностью
скажите мне простой метод, как резервное копирование и восстановление данных NV На Hiscilicon на базе процессора
делает qpst работу инструмента для этого?

**Comment by forth32** [comment]
Try to use fastboot interface of usbloader:
1. load usbloader in fastboot mode (balong-usbdload -f usbloader.bin)
2. Restore nvdefault partition from backup image (fastboot flash nvdefault nvdefault.img)
3. Erase nimg partition (fastboot erase nvimg)
4. Reboot router

After this, kernel will restore workin nvram (nv.bin) form nvdefault.

**Comment by alirazam** [comment]
i run normal loader from this method
(shift+rignt click) open cmd here .
next type balong_usbdload -p usbloader.bin
next 2 port exist 
1>>pc ui interface
2>> application interface
so my question is that how to run usbloader in fastboot mode?

**Comment by chipoza** [comment]
i backup nvdefault.img from my one device and how to restart in another device

**Comment by alilihicham** [comment]
How do I get nvdefault.img

**Comment by faridmay** [comment]
yaw mayhalbouch hna

**Comment by alilihicham** [comment]
hhhhh saha khoya dziri wash kash jdid rani mezelt 7asl m3a limei

**Comment by abassi94** [comment]
Araw7o nbi3lk 
System ta3 imei hhhhh

**Comment by alilihicham** [comment]
abassi94  arwa7 llfb ne7tajek 
https://www.facebook.com/hicham.h.mahcih

**Comment by MrHackmed** [comment]
@chipoza Can you please upload your nvdefault.img file to the internet and share the download link here then, @forth32 can explain to us better on how to restore it to our devices.
